config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :formation_sports
  resources :situation_sports
  resources :formations
  resources :situations
  resources :side_sports
  resources :sides
  resources :sports
  resources :dashboard, only: [:index]
  devise_for :users
end

app/models/sport.rb
# frozen_string_literal: true

class Sport < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: :slugged

  has_many :side_sports
  has_many :sides, through: :side_sports
  has_many :situation_sports
  has_many :formation_sports
  has_many :situations, through: :situation_sports
  has_many :formations, through: :formation_sports

  validates :name, presence: true, uniqueness: { case_sensitive: false }
end

app/controllers/sports_controller.rb
# frozen_string_literal: true

class SportsController < ApplicationController
  before_action :set_sport, only: %i[show edit update destroy]

  # GET /sports or /sports.json
  def index
    @sports = Sport.all.unscoped
  end

  # GET /sports/1 or /sports/1.json
  def show; end

  # GET /sports/new
  def new
    @sport = Sport.new
  end

  # GET /sports/1/edit
  def edit; end

  # POST /sports or /sports.json
  def create
    @sport = Sport.new(sport_params)

    respond_to do |format|
      if @sport.save
        format.html { redirect_to sport_url(@sport), notice: 'Sport was successfully created.' }
        format.json { render :show, status: :created, location: @sport }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @sport.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sports/1 or /sports/1.json
  def update
    respond_to do |format|
      if @sport.update(sport_params)
        format.html { redirect_to sport_url(@sport), notice: 'Sport was successfully updated.' }
        format.json { render :show, status: :ok, location: @sport }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @sport.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sports/1 or /sports/1.json
  def destroy
    @sport.destroy

    respond_to do |format|
      format.html { redirect_to sports_url, notice: 'Sport was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_sport
    @sport = Sport.friendly.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def sport_params
    params.require(:sport).permit(:name, :slug, :description, :active)
  end
end

app/helpers/sports_helper.rb
# frozen_string_literal: true

module SportsHelper
end

app/views/sports/_form.html.erb
<%= form_with(model: sport) do |form| %>
  <% if sport.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(sport.errors.count, "error") %> prohibited this sport from being saved:</h2>

      <ul>
        <% sport.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <% if action_name == 'edit' %>
  <div>
    <%= form.label :slug, style: "display: block" %>
    <%= form.text_field :slug %>
  </div>
  <% end %>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :active, style: "display: block" %>
    <%= form.check_box :active %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/sports/_sport.html.erb
<div id="<%= dom_id sport %>">
  <p>
    <strong>Name:</strong>
    <%= sport.name %>
  </p>

  <p>
    <strong>Slug:</strong>
    <%= sport.slug %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= sport.description %>
  </p>

  <p>
    <strong>Active:</strong>
    <%= sport.active %>
  </p>

</div>

app/views/sports/edit.html.erb
<h1>Editing sport</h1>

<%= render "form", sport: @sport %>

<br>

<div>
  <%= link_to "Show this sport", @sport %> |
  <%= link_to "Back to sports", sports_path %>
</div>

app/views/sports/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Sports</h1>

<%= link_to "New sport", new_sport_path, class: 'btn btn-primary' %>

<table id="sports" class="table table-condensed table-striped table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Slug</th>
      <th>Description</th>
      <th>Active</th>
      <th colspan="2">Actions</th>
    </tr>
  </thead>
  <tbody>
  <% @sports.each do |sport| %>
    <tr>
      <td><%= sport.name %></td>
      <td><%= sport.slug %></td>
      <td><%= sport.description %></td>
      <td><%= sport.active %></td>
      <td><%= link_to  'Edit', sport_path(sport) %></td>
      <td><%= button_to 'Destroy', sport_path(sport), method: :delete %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/sports/new.html.erb
<h1>New sport</h1>

<%= render "form", sport: @sport %>

<br>

<div>
  <%= link_to "Back to sports", sports_path %>
</div>

app/views/sports/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @sport %>

<div>
  <%= link_to "Edit this sport", edit_sport_path(@sport) %> |
  <%= link_to "Back to sports", sports_path %>

  <%= button_to "Destroy this sport", @sport, method: :delete %>
</div>