config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :formation_sports
  resources :situation_sports
  resources :formations
  resources :situations
  resources :side_sports
  resources :sides
  resources :sports
  resources :dashboard, only: [:index]
  devise_for :users
end

app/models/formation_sport.rb
# frozen_string_literal: true

class FormationSport < ApplicationRecord
  belongs_to :formation
  belongs_to :sport
end

app/controllers/formation_sports_controller.rb
# frozen_string_literal: true

class FormationSportsController < ApplicationController
  before_action :set_formation_sport, only: %i[show edit update destroy]

  # GET /formation_sports or /formation_sports.json
  def index
    @formation_sports = FormationSport.all
  end

  # GET /formation_sports/1 or /formation_sports/1.json
  def show; end

  # GET /formation_sports/new
  def new
    @formation_sport = FormationSport.new
  end

  # GET /formation_sports/1/edit
  def edit; end

  # POST /formation_sports or /formation_sports.json
  def create
    @formation_sport = FormationSport.new(formation_sport_params)

    respond_to do |format|
      if @formation_sport.save
        format.html do
          redirect_to formation_sport_url(@formation_sport), notice: 'Formation sport was successfully created.'
        end
        format.json { render :show, status: :created, location: @formation_sport }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @formation_sport.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /formation_sports/1 or /formation_sports/1.json
  def update
    respond_to do |format|
      if @formation_sport.update(formation_sport_params)
        format.html do
          redirect_to formation_sport_url(@formation_sport), notice: 'Formation sport was successfully updated.'
        end
        format.json { render :show, status: :ok, location: @formation_sport }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @formation_sport.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /formation_sports/1 or /formation_sports/1.json
  def destroy
    @formation_sport.destroy

    respond_to do |format|
      format.html { redirect_to formation_sports_url, notice: 'Formation sport was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_formation_sport
    @formation_sport = FormationSport.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def formation_sport_params
    params.require(:formation_sport).permit(:formation_id, :sport_id)
  end
end

app/helpers/formation_sports_helper.rb
# frozen_string_literal: true

module FormationSportsHelper
end

app/views/formation_sports/_form.html.erb
<%= form_with(model: formation_sport) do |form| %>
  <% if formation_sport.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(formation_sport.errors.count, "error") %> prohibited this formation_sport from being saved:</h2>

      <ul>
        <% formation_sport.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :formation_id, style: "display: block" %>
    <%= form.text_field :formation_id %>
  </div>

  <div>
    <%= form.label :sport_id, style: "display: block" %>
    <%= form.text_field :sport_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/formation_sports/_formation_sport.html.erb
<div id="<%= dom_id formation_sport %>">
  <p>
    <strong>Formation:</strong>
    <%= formation_sport.formation_id %>
  </p>

  <p>
    <strong>Sport:</strong>
    <%= formation_sport.sport_id %>
  </p>

</div>

app/views/formation_sports/edit.html.erb
<h1>Editing formation sport</h1>

<%= render "form", formation_sport: @formation_sport %>

<br>

<div>
  <%= link_to "Show this formation sport", @formation_sport %> |
  <%= link_to "Back to formation sports", formation_sports_path %>
</div>

app/views/formation_sports/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Formation sports</h1>

<div id="formation_sports">
  <% @formation_sports.each do |formation_sport| %>
    <%= render formation_sport %>
    <p>
      <%= link_to "Show this formation sport", formation_sport %>
    </p>
  <% end %>
</div>

<%= link_to "New formation sport", new_formation_sport_path %>

app/views/formation_sports/new.html.erb
<h1>New formation sport</h1>

<%= render "form", formation_sport: @formation_sport %>

<br>

<div>
  <%= link_to "Back to formation sports", formation_sports_path %>
</div>

app/views/formation_sports/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @formation_sport %>

<div>
  <%= link_to "Edit this formation sport", edit_formation_sport_path(@formation_sport) %> |
  <%= link_to "Back to formation sports", formation_sports_path %>

  <%= button_to "Destroy this formation sport", @formation_sport, method: :delete %>
</div>