config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :formation_sports
  resources :situation_sports
  resources :formations
  resources :situations
  resources :side_sports
  resources :sides
  resources :sports
  resources :dashboard, only: [:index]
  devise_for :users
end

app/models/situation_sport.rb
# frozen_string_literal: true

class SituationSport < ApplicationRecord
  belongs_to :situation
  belongs_to :sport
end

app/controllers/situation_sports_controller.rb
# frozen_string_literal: true

class SituationSportsController < ApplicationController
  before_action :set_situation_sport, only: %i[show edit update destroy]

  # GET /situation_sports or /situation_sports.json
  def index
    @situation_sports = SituationSport.all
  end

  # GET /situation_sports/1 or /situation_sports/1.json
  def show; end

  # GET /situation_sports/new
  def new
    @situation_sport = SituationSport.new
  end

  # GET /situation_sports/1/edit
  def edit; end

  # POST /situation_sports or /situation_sports.json
  def create
    @situation_sport = SituationSport.new(situation_sport_params)

    respond_to do |format|
      if @situation_sport.save
        format.html do
          redirect_to situation_sport_url(@situation_sport), notice: 'Situation sport was successfully created.'
        end
        format.json { render :show, status: :created, location: @situation_sport }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @situation_sport.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /situation_sports/1 or /situation_sports/1.json
  def update
    respond_to do |format|
      if @situation_sport.update(situation_sport_params)
        format.html do
          redirect_to situation_sport_url(@situation_sport), notice: 'Situation sport was successfully updated.'
        end
        format.json { render :show, status: :ok, location: @situation_sport }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @situation_sport.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /situation_sports/1 or /situation_sports/1.json
  def destroy
    @situation_sport.destroy

    respond_to do |format|
      format.html { redirect_to situation_sports_url, notice: 'Situation sport was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_situation_sport
    @situation_sport = SituationSport.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def situation_sport_params
    params.require(:situation_sport).permit(:situation_id, :sport_id)
  end
end

app/helpers/situation_sports_helper.rb
# frozen_string_literal: true

module SituationSportsHelper
end

app/views/situation_sports/_form.html.erb
<%= form_with(model: situation_sport) do |form| %>
  <% if situation_sport.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(situation_sport.errors.count, "error") %> prohibited this situation_sport from being saved:</h2>

      <ul>
        <% situation_sport.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :situation_id, style: "display: block" %>
    <%= form.text_field :situation_id %>
  </div>

  <div>
    <%= form.label :sport_id, style: "display: block" %>
    <%= form.text_field :sport_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/situation_sports/_situation_sport.html.erb
<div id="<%= dom_id situation_sport %>">
  <p>
    <strong>Situation:</strong>
    <%= situation_sport.situation_id %>
  </p>

  <p>
    <strong>Sport:</strong>
    <%= situation_sport.sport_id %>
  </p>

</div>

app/views/situation_sports/edit.html.erb
<h1>Editing situation sport</h1>

<%= render "form", situation_sport: @situation_sport %>

<br>

<div>
  <%= link_to "Show this situation sport", @situation_sport %> |
  <%= link_to "Back to situation sports", situation_sports_path %>
</div>

app/views/situation_sports/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Situation sports</h1>

<div id="situation_sports">
  <% @situation_sports.each do |situation_sport| %>
    <%= render situation_sport %>
    <p>
      <%= link_to "Show this situation sport", situation_sport %>
    </p>
  <% end %>
</div>

<%= link_to "New situation sport", new_situation_sport_path %>

app/views/situation_sports/new.html.erb
<h1>New situation sport</h1>

<%= render "form", situation_sport: @situation_sport %>

<br>

<div>
  <%= link_to "Back to situation sports", situation_sports_path %>
</div>

app/views/situation_sports/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @situation_sport %>

<div>
  <%= link_to "Edit this situation sport", edit_situation_sport_path(@situation_sport) %> |
  <%= link_to "Back to situation sports", situation_sports_path %>

  <%= button_to "Destroy this situation sport", @situation_sport, method: :delete %>
</div>