config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :formation_sports
  resources :situation_sports
  resources :formations
  resources :situations
  resources :side_sports
  resources :sides
  resources :sports
  resources :dashboard, only: [:index]
  devise_for :users
end

app/models/side.rb
# frozen_string_literal: true

class Side < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: :slugged

  has_many :side_sports
  has_many :sports, through: :side_sports

  validates :name, presence: true, uniqueness: { case_sensitive: false }
end

app/controllers/sides_controller.rb
# frozen_string_literal: true

class SidesController < ApplicationController
  before_action :set_side, only: %i[show edit update destroy]

  # GET /sides or /sides.json
  def index
    @sides = Side.all
  end

  # GET /sides/1 or /sides/1.json
  def show; end

  # GET /sides/new
  def new
    @side = Side.new
  end

  # GET /sides/1/edit
  def edit; end

  # POST /sides or /sides.json
  def create
    @side = Side.new(side_params)

    respond_to do |format|
      if @side.save
        format.html { redirect_to side_url(@side), notice: 'Side was successfully created.' }
        format.json { render :show, status: :created, location: @side }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @side.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sides/1 or /sides/1.json
  def update
    respond_to do |format|
      if @side.update(side_params)
        format.html { redirect_to side_url(@side), notice: 'Side was successfully updated.' }
        format.json { render :show, status: :ok, location: @side }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @side.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sides/1 or /sides/1.json
  def destroy
    @side.destroy

    respond_to do |format|
      format.html { redirect_to sides_url, notice: 'Side was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_side
    @side = Side.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def side_params
    params.require(:side).permit(:name, :slug, :description, :active)
  end
end

app/helpers/sides_helper.rb
# frozen_string_literal: true

module SidesHelper
end

app/views/sides/_form.html.erb
<%= form_with(model: side) do |form| %>
  <% if side.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(side.errors.count, "error") %> prohibited this side from being saved:</h2>

      <ul>
        <% side.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :slug, style: "display: block" %>
    <%= form.text_field :slug %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :active, style: "display: block" %>
    <%= form.check_box :active %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/sides/_side.html.erb
<div id="<%= dom_id side %>">
  <p>
    <strong>Name:</strong>
    <%= side.name %>
  </p>

  <p>
    <strong>Slug:</strong>
    <%= side.slug %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= side.description %>
  </p>

  <p>
    <strong>Active:</strong>
    <%= side.active %>
  </p>

</div>

app/views/sides/edit.html.erb
<h1>Editing side</h1>

<%= render "form", side: @side %>

<br>

<div>
  <%= link_to "Show this side", @side %> |
  <%= link_to "Back to sides", sides_path %>
</div>

app/views/sides/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Sides</h1>

<div id="sides">
  <% @sides.each do |side| %>
    <%= render side %>
    <p>
      <%= link_to "Show this side", side %>
    </p>
  <% end %>
</div>

<%= link_to "New side", new_side_path %>

app/views/sides/new.html.erb
<h1>New side</h1>

<%= render "form", side: @side %>

<br>

<div>
  <%= link_to "Back to sides", sides_path %>
</div>

app/views/sides/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @side %>

<div>
  <%= link_to "Edit this side", edit_side_path(@side) %> |
  <%= link_to "Back to sides", sides_path %>

  <%= button_to "Destroy this side", @side, method: :delete %>
</div>